### ISSUE TITLE
Permutation test graph labelling

### ISSUE THREAD

**Issue by widdowquinn** [KevinMMendez/cimcb_lite#1]
The y-axis in the correlation plot, and the x-axis in the p.d.f. plot produced by `permutation_test()` in `permutation_test.py` show "R^2/Q^2". This could be misread by users as if the y/x axes are presenting a *ratio* of the two metrics, rather than plotting both on the same scale.

Could the axes labels be reasonably changed to something less prone to misreading, e.g. "R^2 or Q^2", "metric", "value", etc?

**Comment by widdowquinn** [comment]
I think this is something that could be considered for the titles of the plots produced by `cb.cross_val.kfold.plot()`, too.

**Comment by KevinMMendez** [comment]
Thanks for the suggestion! I've changed '/' to ' & ' for the plots.
